############################### åŸºæœ¬ä¿¡æ¯ ###############################
info:
  name: Material X
  docs: https://xaoxuu.com/wiki/material-x/
  cdn: # æŠŠå¯¹åº”çš„é‚£ä¸€è¡Œæ³¨é‡Šæ‰å°±ä½¿ç”¨æœ¬åœ°çš„æ–‡ä»¶
    css:
      style: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.5/css/style.css
    js:
      app: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.5/js/app.js
      search: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.5/js/search.js
      volantis: https://cdn.jsdelivr.net/gh/xaoxuu/volantis@1.0/js/volantis.min.js



############################### ä¸»é¢˜é£æ ¼ ###############################
# style: material    # material: å¯¼èˆªæ å’Œæ ‡é¢˜æ èƒŒæ™¯æ˜¯ä¸»é¢˜è‰²
style: pure        # pure: å¯¼èˆªæ å’Œæ ‡é¢˜æ èƒŒæ™¯æ˜¯ç™½è‰²


############################### æœåŠ¡å¼€å…³ ###############################
scrollreveal: true
nodewaves: true
busuanzi: true
# fastclick: true



############################### é»˜è®¤å€¼ ###############################
# éŸ³ä¹æ§ä»¶çš„é»˜è®¤é…ç½®ï¼Œå¦‚æœsidebaræˆ–è€…pageé‡Œæ²¡æœ‰æä¾›ï¼Œå°±å–è¿™é‡Œçš„å‚æ•°
music:
  enable: true      # æ˜¯å¦å¯ç”¨
  color: '#1BCDFC'  # ä¸»é¢˜è‰²
  mode: circulation # random ï¼ˆéšæœºï¼‰ single ï¼ˆå•æ›²ï¼‰ circulation ï¼ˆåˆ—è¡¨å¾ªç¯ï¼‰ order ï¼ˆåˆ—è¡¨ï¼‰
  server: netease   # neteaseï¼ˆç½‘æ˜“äº‘éŸ³ä¹ï¼‰tencentï¼ˆQQéŸ³ä¹ï¼‰ xiamiï¼ˆè™¾ç±³ï¼‰ kugouï¼ˆé…·ç‹—ï¼‰
  type: playlist    # song ï¼ˆå•æ›²ï¼‰ album ï¼ˆä¸“è¾‘ï¼‰ playlist ï¼ˆæ­Œå•ï¼‰ search ï¼ˆæœç´¢ï¼‰
  id: 2615636388    # æ­Œæ›²/ä¸“è¾‘/æ­Œå• ID
  volume: 0.7       # éŸ³é‡, 0~1
  autoplay: false   # è‡ªåŠ¨æ’­æ”¾

# å‹é“¾é¡µå¤´åƒå ä½å›¾
avatar_placeholder: https://qiniuyun.ningdali.com/mybloglogo/camelopard.jpg

# æ—¥æœŸæ ¼å¼ http://momentjs.com/docs/
date_format: 'YYYY-MM-DD' # æ–‡ç« å‘å¸ƒæ—¥æœŸçš„æ ¼å¼
updated_date_format: 'll' # æ–‡ç« æ›´æ–°æ—¥æœŸçš„æ ¼å¼

# å¹»ç¯ç‰‡
backstretch:
  position: cover  # cover: å°é¢èƒŒæ™¯   full: æ•´ä¸ªç½‘é¡µèƒŒæ™¯
  duration: 6000 # æŒç»­æ—¶é—´ï¼ˆæ¯«ç§’ï¼‰
  fade: 2500     # æ¸å˜ï¼ˆæ¯«ç§’ï¼‰
  images:
    - https://qiniuyun.ningdali.com/mybloglogo/background.jpg



############################### è‡ªå®šä¹‰ ###############################
# pageçš„å°é¢
cover:
  scheme: search    # åæœŸå°†ä¼šæä¾›å¤šç§å°é¢æ–¹æ¡ˆ
  # height: half      # fullï¼ˆé»˜è®¤å€¼ï¼‰: é¦–é¡µå°é¢å æ®æ•´ä¸ªç¬¬ä¸€å±å¹•ï¼Œå…¶ä»–é¡µé¢å åŠä¸ªå±å¹•é«˜åº¦ï¼Œ half: æ‰€æœ‰é¡µé¢éƒ½å°é¢éƒ½åªå åŠä¸ªå±å¹•é«˜åº¦
  title: "Camelopard Ning's Blog ğŸ¦’"
  logo: https://qiniuyun.ningdali.com/mybloglogo/camelopard.jpg   # logoå’Œtitleåªæ˜¾ç¤ºä¸€ä¸ªï¼Œè‹¥åŒæ—¶è®¾ç½®ï¼Œåˆ™åªæ˜¾ç¤ºlogo
  # search_placeholder: 'æœç´¢'
  # ä¸»é¡µå°é¢èœå•
  features:
    - name: åšæ–‡
      icon: fas fa-rss
      url: /
    - name: é¡¹ç›®
      icon: fas fa-code-branch
      url: projects/
    - name: å‹é“¾
      icon: fas fa-link
      url: friends/
      rel: nofollow
    - name: å…³äº
      icon: fas fa-info-circle
      url: about/
      rel: nofollow


# æ¡Œé¢ç«¯å¯¼èˆªæ èœå•
menu_desktop:
  - name: ç¤ºä¾‹
    icon: fas fa-grin
    url: /
  - name: åˆ†ç±»
    icon: fas fa-folder-open
    url: categories/
    rel: nofollow
  - name: æ ‡ç­¾
    icon: fas fa-hashtag
    url: tags/
    rel: nofollow
  - name: å½’æ¡£
    icon: fas fa-archive
    url: archives/
    rel: nofollow

# æ‰‹æœºç«¯å¯¼èˆªèœå•ï¼ˆä»å³ä¸Šè§’çš„æŒ‰é’®ç‚¹å‡»å±•å¼€ï¼‰
menu_mobile:
  - name: è¿‘æœŸæ–‡ç« 
    icon: fas fa-clock
    url: /
  - name: æ–‡ç« å½’æ¡£
    icon: fas fa-archive
    url: archives/
    rel: nofollow
  - name: å¼€æºé¡¹ç›®
    icon: fas fa-code-branch
    url: projects/
  - name: æˆ‘çš„å‹é“¾
    icon: fas fa-link
    url: friends/
    rel: nofollow
  - name: ä¸»é¢˜æ–‡æ¡£
    icon: fas fa-book
    url: https://xaoxuu.com/wiki/material-x/
    rel: nofollow
  - name: å…³äºå°ç«™
    icon: fas fa-info-circle
    url: about/
    rel: nofollow

# é»˜è®¤çš„metaä¿¡æ¯ï¼Œæ–‡ç« ä¸­æ²¡æœ‰é…ç½®åˆ™æŒ‰ç…§è¿™é‡Œçš„é…ç½®æ¥æ˜¾ç¤ºï¼Œè®¾ç½®ä¸ºfalseåˆ™ä¸æ˜¾ç¤º
# å…¶ä¸­ï¼Œtitleåªåœ¨headerä¸­æœ‰æ•ˆï¼Œmusicå’Œthumbnailæ— éœ€åœ¨è¿™é‡Œè®¾ç½®ï¼Œæ–‡ç« ä¸­æœ‰åˆ™æ˜¾ç¤º
# å¦‚æœtagsæ”¾ç½®åœ¨meta.headerä¸­ï¼Œé‚£ä¹ˆåœ¨poståˆ—è¡¨ä¸­ä¸æ˜¾ç¤ºï¼ˆå› ä¸ºå¡ç‰‡ä¸‹æ–¹å·²ç»æœ‰äº†ï¼‰
meta:
  header: [title, author, date, categories, counter, top]
  footer: [updated, tags, share]

# ä¸»ä½“å…ƒç´ ï¼Œä½ ä¹Ÿå¯ä»¥åœ¨é¡µé¢çš„Front-matterä¸­è®¾ç½®
body: [article, comments]

# ä¾§è¾¹æ å°éƒ¨ä»¶ï¼Œé»˜è®¤æŒ‰ä¸‹é¢ç»™å®šçš„é¡ºåºå…¨éƒ¨æ˜¾ç¤ºï¼Œæ–‡ç« ä¸­è¿˜å¯ä»¥è‡ªå®šä¹‰æ˜¾ç¤ºä¸€éƒ¨åˆ†ä»¥åŠé¡ºåº
sidebar:
  - widget: author
    avatar: https://qiniuyun.ningdali.com/mybloglogo/camelopard.jpg
    social: true
  - widget: toc
  - widget: grid
    icon: fas fa-map-signs
    title: ç«™å†…å¯¼èˆª
    rows:
      - name: è¿‘æœŸæ–‡ç« 
        icon: fas fa-clock
        url: /
      - name: æ–‡ç« å½’æ¡£
        icon: fas fa-archive
        url: archives/
        rel: nofollow
      - name: å¼€æºé¡¹ç›®
        icon: fas fa-code-branch
        url: projects/
      - name: æˆ‘çš„å‹é“¾
        icon: fas fa-link
        url: friends/
        rel: nofollow
      - name: å…³äºå°ç«™
        icon: fas fa-info-circle
        url: about/
        rel: nofollow
  - widget: category
    more:
      icon: fas fa-expand-arrows-alt
      url: categories/
      rel: nofollow
  - widget: tagcloud
    icon: fas fa-fire
    more:
      icon: fas fa-expand-arrows-alt
      url: tags/
      rel: nofollow
  # - widget: related_posts # éœ€è¦å®‰è£…æ’ä»¶  npm i -S hexo-related-popular-posts
  - widget: music
    icon: fas fa-compact-disc
    title: "æœ€è¿‘åœ¨å¬"
    more:
      icon: far fa-heart
      url: https://y.qq.com/n/yqq/playlist/7013966484.html
      rel: external nofollow noopener noreferrer
      target: _blank
    server: tencent   # neteaseï¼ˆç½‘æ˜“äº‘éŸ³ä¹ï¼‰tencentï¼ˆQQéŸ³ä¹ï¼‰ xiamiï¼ˆè™¾ç±³ï¼‰ kugouï¼ˆé…·ç‹—ï¼‰
    type: playlist    # song ï¼ˆå•æ›²ï¼‰ album ï¼ˆä¸“è¾‘ï¼‰ playlist ï¼ˆæ­Œå•ï¼‰ search ï¼ˆæœç´¢ï¼‰
    id: 7013966484     # æ­Œæ›²/ä¸“è¾‘/æ­Œå• ID


# ç¤¾äº¤ä¿¡æ¯
social:
  - icon: fas fa-rss
    url: atom.xml
  - icon: fas fa-envelope
    url: mailto:mrning@gmail.com
  - icon: fab fa-github
    url: https://github.com/MrDalili
  - icon: fas fa-headphones-alt
    url: https://y.qq.com/n/yqq/playlist/7013966484.html


# åˆ†äº«æŒ‰é’®
# å½“idä¸ºqrcodeæ—¶éœ€è¦å®‰è£…æ’ä»¶  npm i -S hexo-helper-qrcode
share:
  - id: qq
    name: QQå¥½å‹
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qq.png
  - id: qzone
    name: QQç©ºé—´
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qzone.png
  # - id: qrcode
  #   name: å¾®ä¿¡
  #   img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/wechat.png
  - id: weibo
    name: å¾®åš
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/weibo.png
  # - id: qrcode
  #   name: QRcode
  #   img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qrcode.png



# footer: 'é¡µè„šæ–‡å­—ï¼Œæ”¯æŒ[markdown](/)'


############################### è¯„è®ºç³»ç»Ÿ ###############################

# disqus_shortname: è¦ä½¿ç”¨å“ªä¸ªè¯·å¤åˆ¶åˆ°æ ¹ç›®å½•é…ç½®æ–‡ä»¶ï¼
# gitalk: è¦ä½¿ç”¨å“ªä¸ªè¯·å¤åˆ¶åˆ°æ ¹ç›®å½•é…ç½®æ–‡ä»¶ï¼
#   clientID: ä½ çš„clientID
#   clientSecret: ä½ çš„clientSecret
#   repo: ä½ çš„repoå
#   owner: ä½ çš„GitHubå
#   admin: [] è‡³å°‘å¡«å†™ä½ çš„GitHubå
# leancloud: è¦ä½¿ç”¨å“ªä¸ªè¯·å¤åˆ¶åˆ°æ ¹ç›®å½•é…ç½®æ–‡ä»¶ï¼
#   app_id: ä½ çš„appId
#   app_key: ä½ çš„appKey


############################### æ‚é¡¹ï¼Œè¯·å‹¿åˆ é™¤ ###############################
#valineé…ç½®
valine:
  enable: true # å¦‚æœä½ æƒ³ç”¨Valineè¯„è®ºç³»ç»Ÿï¼Œè¯·è®¾ç½®enableä¸ºtrue
  volantis: true # æ˜¯å¦å¯ç”¨volantisç‰ˆæœ¬ï¼ˆç¦æ­¢åŒ¿åï¼Œå¢åŠ è‹¥å¹²è´´å§ã€QQè¡¨æƒ…ï¼‰
  # è¿˜éœ€è¦åœ¨æ ¹ç›®å½•é…ç½®æ–‡ä»¶ä¸­æ·»åŠ ä¸‹é¢è¿™ä¸‰è¡Œå†…å®¹
  # leancloud:
  #   app_id: ä½ çš„appId
  #   app_key: ä½ çš„appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: å¿«æ¥è¯„è®ºå§~ # valine comment input placeholder(like: Please leave your footprints )
  avatar: mp # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: true # valine verify code (true/false)
  notify: true # valine mail notify (true/false)
  lang: zh-cn
  highlight: true

# æœç´¢é…ç½®
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id: 13530543


# Lessæ¸²æŸ“
less:
  compress: true

